### ISSUE TITLE
JSON Client Receiving Malformed JSON returns empty object

### ISSUE THREAD

**Issue by john681611** [restify/clients#145] opened 2017-12-15 14:49 UTC
https://github.com/restify/clients/blob/master/lib/JsonClient.js#L65-L70

Shouldn't this error with message that it failed to parse the JSON

**Comment by DonutEspresso** [comment] 2018-02-07 01:53
Thanks for the report! I'll be submitting a fix for this shortly. Marking this as a dupe of #140

**Closed by DonutEspresso** 2018-02-07 01:53 UTC
